links:
- text: 'Top'
  href: '/?page=top'
- text: 'Blog'
  href: '/?post'
- text: 'Links'
  href: './'
  sublinks:
  - text: 'github'
    href: 'https://github.com/wattlebirdaz'
sociallinks:
- icon: 'fa-twitter-square'
  href: 'https://twitter.com/Twitter'
- icon: 'fa-github-square'
  href: 'https://github.com/wattlebirdaz'
- icon: 'fa-graduation-cap'
  href: 'https://rotaki.org'
twitter: 'OtakiRiki'