protocol: 'https:'
host: 'rotaki.org'
sitetitle: 'Riki Otaki Blog'
sitesubtitle: 'Content Management System written in bash'
links:
- text: 'Top'
  href: '/?page=top'
- text: 'Blog'
  href: '/?post'
- text: 'Profile'
  href: '/?page=profile'
- text: 'Links'
  href: './'
  sublinks:
  - text: 'github'
    href: 'https://github.com/wattlebirdaz'
sociallinks:
- icon: 'fa-twitter-square'
  href: 'https://twitter.com/OtakiRiki'
- icon: 'fa-github-square'
  href: 'https://github.com/wattlebirdaz'
hatena: '@'
pocket: '@'
twitter: 'OtakiRiki'
line: '@'
facebook: '@'