links:
- text: 'top'
  href: '/?page=top'
- text: 'blog'
  href: '/?post'
- text: '外部サイト'
  href: './'
  sublinks:
  - text: 'github'
    href: 'https://github.com/wattlebirdaz'
sociallinks:
- icon: 'fa-twitter-square'
  href: 'https://twitter.com/Twitter'
- icon: 'fa-graduation-cap'
  href: 'top'